### ISSUE TITLE
Correct datis script to real life examples

### ISSUE THREAD

**Issue by tflanary** [rkusa/DATIS#12]
Consider tweaking it slightly to be more precise and aligned to real life.

For example, it would be, 

> Boston Tower Information Delta. One four zero zero Zulu. Wind two five zero at one zero. Visibility one zero. Ceiling four thousand five hundred broken. Temperature three four. Dew point two eight. Altimeter three zero one zero. ILS−DME Runway Two Seven Approach in use. Departing Runway Two Two Right. Hazardous Weather Information for (geographical area) available on HIWAS or Flight Service Frequencies. Advise on initial contact you have Delta.”

https://www.faa.gov/documentLibrary/media/Order/ATC.pdf
Example on page 106

**Comment by rkusa** [comment]
Hi, I'd say that this is definitely a valid request. However, I had this discussion in hoggit's discord multiple times already and the outcome always was that there is no such thing as a "the correct ATIS report". While ATIS messages in the US seem to be at least somehow consistent, in Europe they are quite different from airport to airport. So if I do a one to one copy of a US ATIS report, pilots knowing European ATIS messages might get unhappy.

That being said, I tried to create the message according to the following criteria:
- only add information we get out of DCS
- even if not "realistic", add different QNH formats to have the ATIS work for different DCS aircrafts
- find a way that the two points above are still structured as "realistic" as possible.

While this sounds like I am rejecting your suggestion (well, which I at least do for simply coping an example report), I am totally open for improving the current report. Though I'd prefer to have the discussion like: "The current report says 'Runway in use is 3 1', I'd suggest adjusting it to '...', because ...".

What in the example report you posted, would you like to see adjusted in DATIS? 👍

**Comment by rkusa** [comment]
Feel free to re-open with specific suggestions
