### ISSUE TITLE
DATIS not use voice 

### ISSUE THREAD

**Issue by debo87** [rkusa/DATIS#20]
Hi I have a problem with datas, in practice I hear a sound like code morse,(in SR client ATIS station blinking)
[DATIS.log](https://github.com/rkusa/DATIS/files/3743262/DATIS.log). I do not understand what can give problems, from the logs it seems that converts data into text.

**Comment by rkusa** [comment]
From the logs, it looks like ATIS wasn't able to connect to SRS. Possible reasons:

- Is your SRS server running on the same system DCS is?
- Is your SRS server using the default port of 5002?

**Comment by debo87** [comment]
Hi thanks for the answer, then the log says that it is not able to reach srs it because I turned off the data, the server srs and dcs are on the same machine. Silly question but if srs is not installed in its default folder can give problems to DATIS?
I tried with beta srs and the latest build datas and I see that it works...

**Comment by rkusa** [comment]
@slampemil version `0.10.0-beta1` is meant for the upcoming SRS 1.7.0.0 release and is not backward compatible to SRS 1.6. Please use DATIS 0.9 until SRS 1.7 is released. Since I can see that this can easily be missed without going to the change log, I’ll update the release page to explicitly state the SRS version requirement.

@debo87 sounds like it was the same for you. DATIS 0.10 for SRS 1.7 and DATIS 0.9 for SRS 1.6 👍
