### ISSUE TITLE
Feature Request: Allow to configure win voice

### ISSUE THREAD

**Issue by obfuscoder** [rkusa/DATIS#37]
Hi there,

could you please add the possibility to define the voice used with win-tts much like it is possible for the cloud based services? I'm asking for a friend!

**Comment by rkusa** [comment]
Hi, should already be possible. The pattern is the same as for the cloud providers. You can also add a random name as a voice to trigger an error. You'll then find the error in the DATIS logs and it, IIRC, lists all available voices as part of that error. I think I didn't add it to the Readme because I wasn't sure if the voices I have on my machine are always preinstalled on other machines as well.

**Comment by obfuscoder** [comment]
Yeah it is.
