### ISSUE TITLE
DATIS uses Windows default language for TTS

### ISSUE THREAD

**Issue by Marsychen** [rkusa/DATIS#48]
DATIS is somehow using the Windows default langauge for TTS (in my case German)
That changed from previous versions, where the english voice was used for TTS.
This leads to very funny ATIS messages, but they aren't really understandable.

**Comment by rkusa** [comment]
Thanks for the report! Are you using [`1.1.0-rc.1`](https://github.com/rkusa/DATIS/blob/master/CHANGELOG.md#110-rc1---2020-05-17)?

**Comment by rkusa** [comment]
Nevermind, even though I cannot reproduce it without changing my system language, I've added some logic that makes sure to use an English voice by default. The fix is included in https://github.com/rkusa/DATIS/releases/tag/1.1.0
If you don't mind, please let me know if this fixes the issue for you 🙏
Besten Dank

**Comment by Marsychen** [comment]
fixes the issue for us :)
