### ISSUE TITLE
CARRIER stations should use "ninety-nine" vice "99" for TTS engine

### ISSUE THREAD

**Issue by hawaiianryan808** [rkusa/DATIS#66]
USN shorthand for "attention all personnel on this radio net" is 99.

However, when you're reading this as text (likely from your research), you're inclined to present it to the TTS engine as "99" vice "ninety-nine."

Worse, DATIS pre-processes the text string and plugs in "niner" for "9" making it sound doubly wrong (i.e. "niner niner").

Recommending explicitly presenting the string "ninety-nine" vice "99" to the TTS engine for CARRIER stations.

**Comment by rkusa** [comment]
I am indeed explicitly asking the TTS engine to read _niner niner_. Thanks for the report that this is wrong. E.g. [this recording](https://www.youtube.com/watch?v=rDrVkbYlsLM) confirms your report.

I've released a new version ([`2.2.0-beta.4`](https://github.com/rkusa/DATIS/releases/tag/2.2.0-beta.4)) that lets the TTS engine read "99" (reads it as ninety-nine) instead of "niner niner". Does this sound correct to you now?

Thanks for helping improve DATIS :+1:

**Comment by hawaiianryan808** [comment]
Affirm, correct now with "ninety-nine" as shown/heard in the video you linked at time stamp 5m24s and again at 5m44s (and possibly later).

Thanks for making this awesome mod! Happy to help with the operational details.
