### ISSUE TITLE
BRC Reporting True not Magnetic

### ISSUE THREAD

**Issue by CaptainBandages** [rkusa/DATIS#68]
Assigned Carrier 99. Reports BRC 4 degrees off in persian gulf map. I believe its due to the magnetic variation.

LHA/LHD NATOPS MANUAL (NAVAIR 00-80T-106) defines the BRC as: "base recovery course (BRC). The ship’s magnetic heading during flight operations."

**Comment by rkusa** [comment]
Thanks for the report! DATIS should already report BRCs as magnetic headings. Though, since DCS itself does not provide a magnetic derivation to mods, I have to calculate it. The calculation isn't always a 100% correct. However, a difference of 4 degrees shouldn't happen. I've just retested it and I only observed a difference of 1 degree on both Caucasus and Persian gulf. For testing, I compare the BRC report of DATIS with the true heading reported by the F10 map and compare this difference with the MVAR shown in the F18's HSI (DATA -> A/C). Do you have an example (a mission myb?) where you observed an error of 4 degrees?

**Comment by CaptainBandages** [comment]
> Thanks for the report! DATIS should already report BRCs as magnetic headings. Though, since DCS itself does not provide a magnetic derivation to mods, I have to calculate it. The calculation isn't always a 100% correct. However, a difference of 4 degrees shouldn't happen. I've just retested it and I only observed a difference of 1 degree on both Caucasus and Persian gulf. For testing, I compare the BRC report of DATIS with the true heading reported by the F10 map and compare this difference with the MVAR shown in the F18's HSI (DATA -> A/C). Do you have an example (a mission myb?) where you observed an error of 4 degrees?

I just created a Syrian Mission and the BRC it reports is 13 degrees out.

**Comment by rkusa** [comment]
I just tried Syria. DATIS was reporting:

> BRC ZERO 7 5, 
> expected final heading ZERO 6 6, 

The F10 map is showing a carrier heading of 71 degree (in true).

![image](https://user-images.githubusercontent.com/409021/97087708-45c76680-162c-11eb-8fd0-1b00957d6db9.png)

The magnetic variation shown in the F18 is about 5 degrees. According to that, magnetic BRC would be at 76 degree, so DATIS is only 1 deg. off in my test.

![image](https://user-images.githubusercontent.com/409021/97087727-6abbd980-162c-11eb-8fe3-a9087e09bd8e.png)

Would you mind sending me the mission where you saw the 13 degree off? Or do you see something wrong in my test?

**Comment by CaptainBandages** [comment]
There's your issue right there. East variation is subtracted from True to get Magnetic. "East is Least, West is Best"

**Comment by rkusa** [comment]
You are right! I've noticed that simply switching the sign breaks the BRC for Caucasus. So I've looked again into how I try to derive the magnetic variation and it looks like what I am actually calculating is the angle of DCS's grid and not the magnetic variation at all. Which is a huge bummer, because there is just no way to get the variation from DCS. My best bet is probably to use a constant variation per map and ignore that it will not be a 100% correct if you change the year of the mission by a huge factor (e.g. variation on Syria in 2020 is 5°14' while it is 2°40' in 1980). I'll think a bit about it and see what I can do ...

**Comment by CaptainBandages** [comment]
You could pull from a table based on date. From a real pilot perspective a couple of degrees in not a big deal. There are more errors inherently in navigation systems to be that accurate anyway.

**Comment by rkusa** [comment]
Thanks for the encouragement that minor difference are not a big deal. I have an existing proof of concept locally that I am planning to release in the next version (the one after today's release)

**Comment by CaptainBandages** [comment]
Yeah, there are inherent errors in navigations systems to begin with so a degree or 2 isn't huge, but 5 to 10 can make a difference. I challenge any pilot to try to hold a heading within 1 degree handbombing it. Standard is typically plus or minus 10. Depending on what's available for position updating, even with GPS there's some uncertainty and requires augmentation for increased accuracy. A degree off equates to ~75' of error at 3/4NM. Compare that to GNSS without augmentation worst case 330' lateral and 460' vertical, well within the 0.3nm RNP. From a pilot perspective all manageable errors. Everything gets you close, but ultimately you have to use your M1 eyeball to line up and land.

**Comment by rkusa** [comment]
It is finally fixed, thanks again for the report! I've solved it by implementing the International Geomagnetic Reference Field model to calculate magnetic declinations for a location and date. This will get inaccurate for futures dates past 2025, but I've observed the same for DCS. Though, the farther the date in the future, the higher the chance of a deviation from what DCS calculates. For dates between 1900 and 2025 the implemented model and the model DCS uses seem to be similar enough so that inaccuracies are within 1 degree most of the time (at least for the tests I did). Please let me know if you ever encounter a deviation higher than 1 degree for dates between 1900 and 2025 on any map.
