### ISSUE TITLE
Placing 2 ATIS stations at an airfield...only 1 of them works

### ISSUE THREAD

**Issue by matthewbrahms** [rkusa/DATIS#75]

**Comment by matthewbrahms** [comment]
So in NTTR, I was trying to place an ATIS station at Laughlin Airport on FREQ 119.825 and 305.55.  
```
# Laughlin Airport
ATIS Laughlin Airport 119.825, TRAFFIC 123.900, VOICE WIN
ATIS Laughlin Airport 305.550, VOICE WIN
```
The game only picks up the first one, and in the logs I see:
```
2020-12-07T22:11:59.208189400-06:00 ERROR datis_core - ATIS Laughlin Airport failed: No connection could be made because the target machine actively refused it. (os error 10061)
```
I am assuming that this is failing because it is interpreting and trying to instantiate the second one over the first and it is not able to do so?

If that is confirmed to be the case, we can totally close this issue and I will make a PR to the documentation about this edge case!

Thanks!

**Comment by rkusa** [comment]
Your assumption is correct, there can only be one ATIS station per airfield. However, this is not a restriction we need, it would be possible to change the implementation to allow multiple ATIS stations per airfield. Though I have no idea if this is worth the effort. What is your use-case? Different frequencies to provide DATIS to different aircraft types?

The error you've mentioned

```
2020-12-07T22:11:59.208189400-06:00 ERROR datis_core - ATIS Laughlin Airport failed: No connection could be made because the target machine actively refused it. (os error 10061)
```

is unrelated to the deduplication of the ATIS stations. This usually happens when there is no SRS server running. Might that have been the case for you?

**Comment by rkusa** [comment]
I'll close this for now as a "feature". I am happy to consider allowing multiple stations per airfield if there is a use-case for it. So if anyone stumbling upon this comment, please let me know your use-case if you have one.

**Comment by Commiccannon** [comment]
Hey, having the same issues, trying to get a uhf and a vhf frequency so multiple aircraft with radio restrictions ie the viper can only have one uhf and one vhf, if one radio is used for the tower then we cannot have the atis on the other etc. Is there any chance this could be added please?
