### ISSUE TITLE
Wind Pronunciation and Game Time

### ISSUE THREAD

**Issue by dbnewell** [rkusa/DATIS#80]
Is it possible to change the spelling of "wind" in the code so when it is sent to the tts is is pronounced correctly? possibly change it to "wend" or "whend"? Could the in game time in zulu time be added to the automated ATIS broadcast? Thanks

**Comment by rkusa** [comment]
> possibly change it to "wend" or "whend"?

As a non native English speaking person, I didn't notice that the pronunciation is off, but I'll look into it, thanks for the feedback!

> Could the in game time in zulu time be added to the automated ATIS broadcast?

I'd probably tend to avoid that to reduce the amount of TTS that is necessary, because right now, the result of TTS is cached and reused until the report changes. This reduces the costs for AWS/GCloud based TTS significantly (see also https://github.com/rkusa/DATIS/issues/77).  What would be your use-case for this?

**Comment by dbnewell** [comment]
Thank you for looking into the pronunciation issue with “wind”!

The in game time in zulu time would be very beneficial to our squadron operations, mission starts, flight departures etc, It would also get the report another step closer to a true to life ATIS report …. Would it be a possibility to add it as an optional function to enable or disable in the ATIS reports as we are using the windows tts implementation for the ATIS reports on our servers? I understand the need to cache the report and limit the report changes for using external tts services.  

Thank you 
Doug

Sent from Mail for Windows 10

**Comment by rkusa** [comment]
> Would it be a possibility to add it as an optional function to enable or disable in the ATIS reports as we are using the windows tts implementation for the ATIS reports on our servers? I understand the need to cache the report and limit the report changes for using external tts services.

Since it doesn't really matter for WIN TTS, having it as an optional feature would be a valid approach. I just remembered that I often  see mission time differences between different pilots in MP. So having it in the ATIS report might even be an easy way of having a somewhat accurate time sync 🤔

**Comment by rkusa** [comment]
@dbnewell I've looked into the _wind_ pronunciation and it sounds correct to me (though I am not a native English speaker). Still, which TTS voice are you using where you'd say that the pronunciation could be improved?

**Comment by dbnewell** [comment]
I am using the windows tts implementation and I have tried it with all standard English voices with the same result.  It is currently being pronounced as “wind” like you wind up your clock. I did a custom broadcast and for it to have the correct pronunciation I had to spell it “whend” or “wend”. Hope this helps and does not make it confusing. 


Thank you 
Doug



Sent from Mail for Windows 10

**Comment by rkusa** [comment]
I must have tested GCloud or AWS instead of WIN TTS, since it is indeed quite obvious wrong with WIN TTS. It is fixed now, and will be released in the next couple of days as part of `2.2.1`. Thanks for the report, while a small change, I think it is has quite a good impact on immersion! If you hear anything else where the pronunciation is off, please let me know.

**Comment by dbnewell** [comment]
Thank you, I look forward to passing this information along to my squadron mates!
